/* Export template_translations from the DB back to the committed per-language
 * files at server/data/translations/{lang}.json, so production picks them up
 * via importTranslations() on boot.
 *
 *   npm run translate:export -w server
 *
 * Companion to translate-templates.ts (AI → DB). Typical refresh cycle:
 *   1. seed (new English)            → templates updated
 *   2. translate:templates --force   → AI writes template_translations (DB)
 *   3. translate:export              → DB written back to the {lang}.json files
 *   4. commit the files; boot import propagates them to production.
 *
 * Each file keeps its _language / _instructions header (if it already exists)
 * and gets one section per template slug: { field: translatedValue }. */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { db } from './index.js';
import { config } from '../config.js';

// Native names for any file we have to create from scratch (existing files
// already carry their own _language, which we preserve).
const NATIVE: Record<string, string> = {
  pl: 'Polski', ro: 'Română', pa: 'ਪੰਜਾਬੀ', ur: 'اردو', pt: 'Português',
  es: 'Español', bn: 'বাংলা', gu: 'ગુજરાતી', it: 'Italiano', cy: 'Cymraeg',
};

function main() {
  const dir = path.resolve(config.paths.serverRoot, 'data', 'translations');
  fs.mkdirSync(dir, { recursive: true });

  const rows = db
    .prepare(
      `SELECT t.slug AS slug, tt.language AS language, tt.content_json AS content_json
         FROM template_translations tt JOIN templates t ON t.id = tt.template_id
        ORDER BY tt.language, t.slug`
    )
    .all() as Array<{ slug: string; language: string; content_json: string }>;

  // Group by language.
  const byLang = new Map<string, Array<{ slug: string; content: Record<string, string> }>>();
  for (const r of rows) {
    const list = byLang.get(r.language) ?? [];
    list.push({ slug: r.slug, content: JSON.parse(r.content_json || '{}') });
    byLang.set(r.language, list);
  }

  let written = 0;
  for (const [lang, sections] of byLang) {
    const file = path.join(dir, `${lang}.json`);
    let doc: Record<string, unknown> = {};
    if (fs.existsSync(file)) {
      doc = JSON.parse(fs.readFileSync(file, 'utf8')) as Record<string, unknown>;
    } else {
      doc._language = NATIVE[lang] ?? lang;
      doc._instructions = 'Each top-level key (other than _language/_instructions) is a template slug; its value maps leaflet field keys to the translated string. Generated by translate:export.';
    }
    for (const s of sections) doc[s.slug] = s.content;
    fs.writeFileSync(file, JSON.stringify(doc, null, 2) + '\n', 'utf8');
    written += 1;
    console.log(`  ${lang}.json: ${sections.map((s) => s.slug).join(', ')}`);
  }
  console.log(`Exported ${rows.length} translation rows to ${written} files.`);
}

const thisFile = fileURLToPath(import.meta.url);
const entry = process.argv[1] ? path.resolve(process.argv[1]) : '';
if (entry && (entry === thisFile || entry.endsWith('export-translations.ts') || entry.endsWith('export-translations.js'))) {
  main();
}
